version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: groovehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mithun2303
    # ports:
    #   - "5433:5433"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    # ports:
    #   - "8000:8000"
    depends_on:
      - postgres


  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    # ports:
    #   - "3000:3000"
    depends_on:
      - backend
    # command: npm run dev
    tty: true
    # environment:
    #   - REACT_APP_API_URL=http://server:3000
