FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install
# RUN nodemon server
# COPY . .

# EXPOSE 8000

CMD ["npm", "start"]


# FROM node:14

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 3001

# CMD ["npm", "start"]
